"""Lockfile manager — reads and writes both text and JSON lockfiles.

Lockfile formats
----------------
``requirements.lock``
    Plain-text, pip-compatible pinned requirements (one ``pkg==x.y.z`` per
    line).

``requirements.lock.json``
    Structured JSON with package metadata::

        {
            "lockfile_version": "1",
            "created_at": "2026-02-15T19:50:00+05:30",
            "dependencies": {
                "numpy": {
                    "version": "1.26.4",
                    "hash": "sha256:..."
                }
            }
        }
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ppmm_lock.resolver import ResolvedDependency

# Default file names
LOCK_TEXT = "requirements.lock"
LOCK_JSON = "requirements.lock.json"


# ======================================================================
# Writing
# ======================================================================

def generate_lockfile(
    resolved: dict[str, ResolvedDependency],
    directory: Path | None = None,
) -> tuple[Path, Path]:
    """Write both text and JSON lockfiles to *directory*.

    Parameters
    ----------
    resolved:
        Mapping of package name → ``ResolvedDependency`` as returned by
        :func:`ppmm_lock.resolver.resolve_dependencies`.
    directory:
        Target directory (defaults to CWD).

    Returns
    -------
    tuple[Path, Path]
        Paths to the generated text and JSON lockfiles.
    """
    directory = directory or Path.cwd()

    text_path = directory / LOCK_TEXT
    json_path = directory / LOCK_JSON

    # --- Text lockfile ---
    sorted_deps = sorted(resolved.values(), key=lambda d: d.name)
    lines = [f"{dep.name}=={dep.version}" for dep in sorted_deps]
    text_path.write_text(
        "# Auto-generated by ppmm-lock. DO NOT EDIT.\n"
        + "\n".join(lines)
        + "\n",
        encoding="utf-8",
    )

    # --- JSON lockfile ---
    json_data: dict[str, Any] = {
        "lockfile_version": "1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "dependencies": {},
    }
    for dep in sorted_deps:
        entry: dict[str, Any] = {"version": dep.version}
        if dep.hash:
            entry["hash"] = dep.hash
        json_data["dependencies"][dep.name] = entry

    json_path.write_text(
        json.dumps(json_data, indent=2) + "\n",
        encoding="utf-8",
    )

    return text_path, json_path


# ======================================================================
# Reading
# ======================================================================

def read_lockfile(directory: Path | None = None) -> dict[str, ResolvedDependency]:
    """Read the JSON lockfile from *directory* and return resolved deps.

    Falls back to parsing the text lockfile if the JSON variant is missing.

    Parameters
    ----------
    directory:
        Directory containing the lockfile(s). Defaults to CWD.

    Returns
    -------
    dict[str, ResolvedDependency]

    Raises
    ------
    FileNotFoundError
        If neither lockfile exists.
    """
    directory = directory or Path.cwd()

    json_path = directory / LOCK_JSON
    text_path = directory / LOCK_TEXT

    if json_path.exists():
        return _read_json_lockfile(json_path)
    if text_path.exists():
        return _read_text_lockfile(text_path)
    raise FileNotFoundError(
        f"No lockfile found in {directory}. Run 'ppmm-lock lock' first."
    )


def lockfile_exists(directory: Path | None = None) -> bool:
    """Return ``True`` if a text lockfile exists in *directory*."""
    directory = directory or Path.cwd()
    return (directory / LOCK_TEXT).exists()


# ======================================================================
# Internal parsers
# ======================================================================

def _read_json_lockfile(path: Path) -> dict[str, ResolvedDependency]:
    data = json.loads(path.read_text(encoding="utf-8"))
    deps: dict[str, ResolvedDependency] = {}
    for name, info in data.get("dependencies", {}).items():
        deps[name] = ResolvedDependency(
            name=name,
            version=info["version"],
            hash=info.get("hash"),
        )
    return deps


def _read_text_lockfile(path: Path) -> dict[str, ResolvedDependency]:
    deps: dict[str, ResolvedDependency] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "==" in line:
            name, version = line.split("==", 1)
            deps[name.strip().lower()] = ResolvedDependency(
                name=name.strip().lower(), version=version.strip()
            )
    return deps
